/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppHomeRouteImport } from './routes/app.home'
import { Route as CfpEventSlugRouteImport } from './routes/cfp.$eventSlug'
import { Route as ESlugRouteImport } from './routes/e.$slug'
import { Route as EmbedSlugRouteImport } from './routes/embed.$slug'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as PortalEventSlugRouteImport } from './routes/portal.$eventSlug'
import { Route as AppEEventSlugRouteImport } from './routes/app.e.$eventSlug'
import { Route as AppOrgOrgSlugRouteImport } from './routes/app.org.$orgSlug'
import { Route as CfpEventSlugIndexRouteImport } from './routes/cfp.$eventSlug.index'
import { Route as CfpEventSlugSubmitRouteImport } from './routes/cfp.$eventSlug.submit'
import { Route as EmbedWEmbedIdRouteImport } from './routes/embed.w.$embedId'
import { Route as AppEEventSlugIndexRouteImport } from './routes/app.e.$eventSlug.index'
import { Route as AppEEventSlugAgendaRouteImport } from './routes/app.e.$eventSlug.agenda'
import { Route as AppEEventSlugCfpRouteImport } from './routes/app.e.$eventSlug.cfp'
import { Route as AppEEventSlugCommsRouteImport } from './routes/app.e.$eventSlug.comms'
import { Route as AppEEventSlugDashboardRouteImport } from './routes/app.e.$eventSlug.dashboard'
import { Route as AppEEventSlugDetailsRouteImport } from './routes/app.e.$eventSlug.details'
import { Route as AppEEventSlugImportRouteImport } from './routes/app.e.$eventSlug.import'
import { Route as AppEEventSlugProposalsRouteImport } from './routes/app.e.$eventSlug.proposals'
import { Route as AppEEventSlugPublishRouteImport } from './routes/app.e.$eventSlug.publish'
import { Route as AppEEventSlugReviewsRouteImport } from './routes/app.e.$eventSlug.reviews'
import { Route as AppEEventSlugSettingsRouteImport } from './routes/app.e.$eventSlug.settings'
import { Route as AppEEventSlugTasksRouteImport } from './routes/app.e.$eventSlug.tasks'
import { Route as AppEEventSlugTeamRouteImport } from './routes/app.e.$eventSlug.team'
import { Route as CfpEventSlugProposalProposalIdRouteImport } from './routes/cfp.$eventSlug.proposal.$proposalId'
import { Route as AppEEventSlugSessionsIndexRouteImport } from './routes/app.e.$eventSlug.sessions.index'
import { Route as AppEEventSlugSessionsSessionIdRouteImport } from './routes/app.e.$eventSlug.sessions.$sessionId'
import { Route as AppEEventSlugSpeakersIndexRouteImport } from './routes/app.e.$eventSlug.speakers.index'
import { Route as AppEEventSlugSpeakersEventContactIdRouteImport } from './routes/app.e.$eventSlug.speakers.$eventContactId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const CfpEventSlugRoute = CfpEventSlugRouteImport.update({
  id: '/cfp/$eventSlug',
  path: '/cfp/$eventSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ESlugRoute = ESlugRouteImport.update({
  id: '/e/$slug',
  path: '/e/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedSlugRoute = EmbedSlugRouteImport.update({
  id: '/embed/$slug',
  path: '/embed/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalEventSlugRoute = PortalEventSlugRouteImport.update({
  id: '/portal/$eventSlug',
  path: '/portal/$eventSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEEventSlugRoute = AppEEventSlugRouteImport.update({
  id: '/e/$eventSlug',
  path: '/e/$eventSlug',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgOrgSlugRoute = AppOrgOrgSlugRouteImport.update({
  id: '/org/$orgSlug',
  path: '/org/$orgSlug',
  getParentRoute: () => AppRoute,
} as any)
const CfpEventSlugIndexRoute = CfpEventSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CfpEventSlugRoute,
} as any)
const CfpEventSlugSubmitRoute = CfpEventSlugSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => CfpEventSlugRoute,
} as any)
const EmbedWEmbedIdRoute = EmbedWEmbedIdRouteImport.update({
  id: '/embed/w/$embedId',
  path: '/embed/w/$embedId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEEventSlugIndexRoute = AppEEventSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEEventSlugRoute,
} as any)
const AppEEventSlugAgendaRoute = AppEEventSlugAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppEEventSlugRoute,
} as any)
const AppEEventSlugCfpRoute = AppEEventSlugCfpRouteImport.update({
  id: '/cfp',
  path: '/cfp',
  getParentRoute: () => AppEEventSlugRoute,
} as any)
const AppEEventSlugCommsRoute = AppEEventSlugCommsRouteImport.update({
  id: '/comms',
  path: '/comms',
  getParentRoute: () => AppEEventSlugRoute,
} as any)
const AppEEventSlugDashboardRoute = AppEEventSlugDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppEEventSlugRoute,
} as any)
const AppEEventSlugDetailsRoute = AppEEventSlugDetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => AppEEventSlugRoute,
} as any)
const AppEEventSlugImportRoute = AppEEventSlugImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppEEventSlugRoute,
} as any)
const AppEEventSlugProposalsRoute = AppEEventSlugProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => AppEEventSlugRoute,
} as any)
const AppEEventSlugPublishRoute = AppEEventSlugPublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => AppEEventSlugRoute,
} as any)
const AppEEventSlugReviewsRoute = AppEEventSlugReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AppEEventSlugRoute,
} as any)
const AppEEventSlugSettingsRoute = AppEEventSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppEEventSlugRoute,
} as any)
const AppEEventSlugTasksRoute = AppEEventSlugTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppEEventSlugRoute,
} as any)
const AppEEventSlugTeamRoute = AppEEventSlugTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppEEventSlugRoute,
} as any)
const CfpEventSlugProposalProposalIdRoute =
  CfpEventSlugProposalProposalIdRouteImport.update({
    id: '/proposal/$proposalId',
    path: '/proposal/$proposalId',
    getParentRoute: () => CfpEventSlugRoute,
  } as any)
const AppEEventSlugSessionsIndexRoute =
  AppEEventSlugSessionsIndexRouteImport.update({
    id: '/sessions/',
    path: '/sessions/',
    getParentRoute: () => AppEEventSlugRoute,
  } as any)
const AppEEventSlugSessionsSessionIdRoute =
  AppEEventSlugSessionsSessionIdRouteImport.update({
    id: '/sessions/$sessionId',
    path: '/sessions/$sessionId',
    getParentRoute: () => AppEEventSlugRoute,
  } as any)
const AppEEventSlugSpeakersIndexRoute =
  AppEEventSlugSpeakersIndexRouteImport.update({
    id: '/speakers/',
    path: '/speakers/',
    getParentRoute: () => AppEEventSlugRoute,
  } as any)
const AppEEventSlugSpeakersEventContactIdRoute =
  AppEEventSlugSpeakersEventContactIdRouteImport.update({
    id: '/speakers/$eventContactId',
    path: '/speakers/$eventContactId',
    getParentRoute: () => AppEEventSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/home': typeof AppHomeRoute
  '/cfp/$eventSlug': typeof CfpEventSlugRouteWithChildren
  '/e/$slug': typeof ESlugRoute
  '/embed/$slug': typeof EmbedSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/portal/$eventSlug': typeof PortalEventSlugRoute
  '/app/': typeof AppIndexRoute
  '/app/e/$eventSlug': typeof AppEEventSlugRouteWithChildren
  '/app/org/$orgSlug': typeof AppOrgOrgSlugRoute
  '/cfp/$eventSlug/submit': typeof CfpEventSlugSubmitRoute
  '/embed/w/$embedId': typeof EmbedWEmbedIdRoute
  '/cfp/$eventSlug/': typeof CfpEventSlugIndexRoute
  '/app/e/$eventSlug/agenda': typeof AppEEventSlugAgendaRoute
  '/app/e/$eventSlug/cfp': typeof AppEEventSlugCfpRoute
  '/app/e/$eventSlug/comms': typeof AppEEventSlugCommsRoute
  '/app/e/$eventSlug/dashboard': typeof AppEEventSlugDashboardRoute
  '/app/e/$eventSlug/details': typeof AppEEventSlugDetailsRoute
  '/app/e/$eventSlug/import': typeof AppEEventSlugImportRoute
  '/app/e/$eventSlug/proposals': typeof AppEEventSlugProposalsRoute
  '/app/e/$eventSlug/publish': typeof AppEEventSlugPublishRoute
  '/app/e/$eventSlug/reviews': typeof AppEEventSlugReviewsRoute
  '/app/e/$eventSlug/settings': typeof AppEEventSlugSettingsRoute
  '/app/e/$eventSlug/tasks': typeof AppEEventSlugTasksRoute
  '/app/e/$eventSlug/team': typeof AppEEventSlugTeamRoute
  '/cfp/$eventSlug/proposal/$proposalId': typeof CfpEventSlugProposalProposalIdRoute
  '/app/e/$eventSlug/': typeof AppEEventSlugIndexRoute
  '/app/e/$eventSlug/sessions/$sessionId': typeof AppEEventSlugSessionsSessionIdRoute
  '/app/e/$eventSlug/speakers/$eventContactId': typeof AppEEventSlugSpeakersEventContactIdRoute
  '/app/e/$eventSlug/sessions/': typeof AppEEventSlugSessionsIndexRoute
  '/app/e/$eventSlug/speakers/': typeof AppEEventSlugSpeakersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/home': typeof AppHomeRoute
  '/e/$slug': typeof ESlugRoute
  '/embed/$slug': typeof EmbedSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/portal/$eventSlug': typeof PortalEventSlugRoute
  '/app': typeof AppIndexRoute
  '/app/org/$orgSlug': typeof AppOrgOrgSlugRoute
  '/cfp/$eventSlug/submit': typeof CfpEventSlugSubmitRoute
  '/embed/w/$embedId': typeof EmbedWEmbedIdRoute
  '/cfp/$eventSlug': typeof CfpEventSlugIndexRoute
  '/app/e/$eventSlug/agenda': typeof AppEEventSlugAgendaRoute
  '/app/e/$eventSlug/cfp': typeof AppEEventSlugCfpRoute
  '/app/e/$eventSlug/comms': typeof AppEEventSlugCommsRoute
  '/app/e/$eventSlug/dashboard': typeof AppEEventSlugDashboardRoute
  '/app/e/$eventSlug/details': typeof AppEEventSlugDetailsRoute
  '/app/e/$eventSlug/import': typeof AppEEventSlugImportRoute
  '/app/e/$eventSlug/proposals': typeof AppEEventSlugProposalsRoute
  '/app/e/$eventSlug/publish': typeof AppEEventSlugPublishRoute
  '/app/e/$eventSlug/reviews': typeof AppEEventSlugReviewsRoute
  '/app/e/$eventSlug/settings': typeof AppEEventSlugSettingsRoute
  '/app/e/$eventSlug/tasks': typeof AppEEventSlugTasksRoute
  '/app/e/$eventSlug/team': typeof AppEEventSlugTeamRoute
  '/cfp/$eventSlug/proposal/$proposalId': typeof CfpEventSlugProposalProposalIdRoute
  '/app/e/$eventSlug': typeof AppEEventSlugIndexRoute
  '/app/e/$eventSlug/sessions/$sessionId': typeof AppEEventSlugSessionsSessionIdRoute
  '/app/e/$eventSlug/speakers/$eventContactId': typeof AppEEventSlugSpeakersEventContactIdRoute
  '/app/e/$eventSlug/sessions': typeof AppEEventSlugSessionsIndexRoute
  '/app/e/$eventSlug/speakers': typeof AppEEventSlugSpeakersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/home': typeof AppHomeRoute
  '/cfp/$eventSlug': typeof CfpEventSlugRouteWithChildren
  '/e/$slug': typeof ESlugRoute
  '/embed/$slug': typeof EmbedSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/portal/$eventSlug': typeof PortalEventSlugRoute
  '/app/': typeof AppIndexRoute
  '/app/e/$eventSlug': typeof AppEEventSlugRouteWithChildren
  '/app/org/$orgSlug': typeof AppOrgOrgSlugRoute
  '/cfp/$eventSlug/submit': typeof CfpEventSlugSubmitRoute
  '/embed/w/$embedId': typeof EmbedWEmbedIdRoute
  '/cfp/$eventSlug/': typeof CfpEventSlugIndexRoute
  '/app/e/$eventSlug/agenda': typeof AppEEventSlugAgendaRoute
  '/app/e/$eventSlug/cfp': typeof AppEEventSlugCfpRoute
  '/app/e/$eventSlug/comms': typeof AppEEventSlugCommsRoute
  '/app/e/$eventSlug/dashboard': typeof AppEEventSlugDashboardRoute
  '/app/e/$eventSlug/details': typeof AppEEventSlugDetailsRoute
  '/app/e/$eventSlug/import': typeof AppEEventSlugImportRoute
  '/app/e/$eventSlug/proposals': typeof AppEEventSlugProposalsRoute
  '/app/e/$eventSlug/publish': typeof AppEEventSlugPublishRoute
  '/app/e/$eventSlug/reviews': typeof AppEEventSlugReviewsRoute
  '/app/e/$eventSlug/settings': typeof AppEEventSlugSettingsRoute
  '/app/e/$eventSlug/tasks': typeof AppEEventSlugTasksRoute
  '/app/e/$eventSlug/team': typeof AppEEventSlugTeamRoute
  '/cfp/$eventSlug/proposal/$proposalId': typeof CfpEventSlugProposalProposalIdRoute
  '/app/e/$eventSlug/': typeof AppEEventSlugIndexRoute
  '/app/e/$eventSlug/sessions/$sessionId': typeof AppEEventSlugSessionsSessionIdRoute
  '/app/e/$eventSlug/speakers/$eventContactId': typeof AppEEventSlugSpeakersEventContactIdRoute
  '/app/e/$eventSlug/sessions/': typeof AppEEventSlugSessionsIndexRoute
  '/app/e/$eventSlug/speakers/': typeof AppEEventSlugSpeakersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/home'
    | '/cfp/$eventSlug'
    | '/e/$slug'
    | '/embed/$slug'
    | '/invite/$token'
    | '/portal/$eventSlug'
    | '/app/'
    | '/app/e/$eventSlug'
    | '/app/org/$orgSlug'
    | '/cfp/$eventSlug/submit'
    | '/embed/w/$embedId'
    | '/cfp/$eventSlug/'
    | '/app/e/$eventSlug/agenda'
    | '/app/e/$eventSlug/cfp'
    | '/app/e/$eventSlug/comms'
    | '/app/e/$eventSlug/dashboard'
    | '/app/e/$eventSlug/details'
    | '/app/e/$eventSlug/import'
    | '/app/e/$eventSlug/proposals'
    | '/app/e/$eventSlug/publish'
    | '/app/e/$eventSlug/reviews'
    | '/app/e/$eventSlug/settings'
    | '/app/e/$eventSlug/tasks'
    | '/app/e/$eventSlug/team'
    | '/cfp/$eventSlug/proposal/$proposalId'
    | '/app/e/$eventSlug/'
    | '/app/e/$eventSlug/sessions/$sessionId'
    | '/app/e/$eventSlug/speakers/$eventContactId'
    | '/app/e/$eventSlug/sessions/'
    | '/app/e/$eventSlug/speakers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/home'
    | '/e/$slug'
    | '/embed/$slug'
    | '/invite/$token'
    | '/portal/$eventSlug'
    | '/app'
    | '/app/org/$orgSlug'
    | '/cfp/$eventSlug/submit'
    | '/embed/w/$embedId'
    | '/cfp/$eventSlug'
    | '/app/e/$eventSlug/agenda'
    | '/app/e/$eventSlug/cfp'
    | '/app/e/$eventSlug/comms'
    | '/app/e/$eventSlug/dashboard'
    | '/app/e/$eventSlug/details'
    | '/app/e/$eventSlug/import'
    | '/app/e/$eventSlug/proposals'
    | '/app/e/$eventSlug/publish'
    | '/app/e/$eventSlug/reviews'
    | '/app/e/$eventSlug/settings'
    | '/app/e/$eventSlug/tasks'
    | '/app/e/$eventSlug/team'
    | '/cfp/$eventSlug/proposal/$proposalId'
    | '/app/e/$eventSlug'
    | '/app/e/$eventSlug/sessions/$sessionId'
    | '/app/e/$eventSlug/speakers/$eventContactId'
    | '/app/e/$eventSlug/sessions'
    | '/app/e/$eventSlug/speakers'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/home'
    | '/cfp/$eventSlug'
    | '/e/$slug'
    | '/embed/$slug'
    | '/invite/$token'
    | '/portal/$eventSlug'
    | '/app/'
    | '/app/e/$eventSlug'
    | '/app/org/$orgSlug'
    | '/cfp/$eventSlug/submit'
    | '/embed/w/$embedId'
    | '/cfp/$eventSlug/'
    | '/app/e/$eventSlug/agenda'
    | '/app/e/$eventSlug/cfp'
    | '/app/e/$eventSlug/comms'
    | '/app/e/$eventSlug/dashboard'
    | '/app/e/$eventSlug/details'
    | '/app/e/$eventSlug/import'
    | '/app/e/$eventSlug/proposals'
    | '/app/e/$eventSlug/publish'
    | '/app/e/$eventSlug/reviews'
    | '/app/e/$eventSlug/settings'
    | '/app/e/$eventSlug/tasks'
    | '/app/e/$eventSlug/team'
    | '/cfp/$eventSlug/proposal/$proposalId'
    | '/app/e/$eventSlug/'
    | '/app/e/$eventSlug/sessions/$sessionId'
    | '/app/e/$eventSlug/speakers/$eventContactId'
    | '/app/e/$eventSlug/sessions/'
    | '/app/e/$eventSlug/speakers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CfpEventSlugRoute: typeof CfpEventSlugRouteWithChildren
  ESlugRoute: typeof ESlugRoute
  EmbedSlugRoute: typeof EmbedSlugRoute
  InviteTokenRoute: typeof InviteTokenRoute
  PortalEventSlugRoute: typeof PortalEventSlugRoute
  EmbedWEmbedIdRoute: typeof EmbedWEmbedIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/home': {
      id: '/app/home'
      path: '/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/cfp/$eventSlug': {
      id: '/cfp/$eventSlug'
      path: '/cfp/$eventSlug'
      fullPath: '/cfp/$eventSlug'
      preLoaderRoute: typeof CfpEventSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$slug': {
      id: '/e/$slug'
      path: '/e/$slug'
      fullPath: '/e/$slug'
      preLoaderRoute: typeof ESlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/$slug': {
      id: '/embed/$slug'
      path: '/embed/$slug'
      fullPath: '/embed/$slug'
      preLoaderRoute: typeof EmbedSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$eventSlug': {
      id: '/portal/$eventSlug'
      path: '/portal/$eventSlug'
      fullPath: '/portal/$eventSlug'
      preLoaderRoute: typeof PortalEventSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/e/$eventSlug': {
      id: '/app/e/$eventSlug'
      path: '/e/$eventSlug'
      fullPath: '/app/e/$eventSlug'
      preLoaderRoute: typeof AppEEventSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/org/$orgSlug': {
      id: '/app/org/$orgSlug'
      path: '/org/$orgSlug'
      fullPath: '/app/org/$orgSlug'
      preLoaderRoute: typeof AppOrgOrgSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/cfp/$eventSlug/': {
      id: '/cfp/$eventSlug/'
      path: '/'
      fullPath: '/cfp/$eventSlug/'
      preLoaderRoute: typeof CfpEventSlugIndexRouteImport
      parentRoute: typeof CfpEventSlugRoute
    }
    '/cfp/$eventSlug/submit': {
      id: '/cfp/$eventSlug/submit'
      path: '/submit'
      fullPath: '/cfp/$eventSlug/submit'
      preLoaderRoute: typeof CfpEventSlugSubmitRouteImport
      parentRoute: typeof CfpEventSlugRoute
    }
    '/embed/w/$embedId': {
      id: '/embed/w/$embedId'
      path: '/embed/w/$embedId'
      fullPath: '/embed/w/$embedId'
      preLoaderRoute: typeof EmbedWEmbedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/e/$eventSlug/': {
      id: '/app/e/$eventSlug/'
      path: '/'
      fullPath: '/app/e/$eventSlug/'
      preLoaderRoute: typeof AppEEventSlugIndexRouteImport
      parentRoute: typeof AppEEventSlugRoute
    }
    '/app/e/$eventSlug/agenda': {
      id: '/app/e/$eventSlug/agenda'
      path: '/agenda'
      fullPath: '/app/e/$eventSlug/agenda'
      preLoaderRoute: typeof AppEEventSlugAgendaRouteImport
      parentRoute: typeof AppEEventSlugRoute
    }
    '/app/e/$eventSlug/cfp': {
      id: '/app/e/$eventSlug/cfp'
      path: '/cfp'
      fullPath: '/app/e/$eventSlug/cfp'
      preLoaderRoute: typeof AppEEventSlugCfpRouteImport
      parentRoute: typeof AppEEventSlugRoute
    }
    '/app/e/$eventSlug/comms': {
      id: '/app/e/$eventSlug/comms'
      path: '/comms'
      fullPath: '/app/e/$eventSlug/comms'
      preLoaderRoute: typeof AppEEventSlugCommsRouteImport
      parentRoute: typeof AppEEventSlugRoute
    }
    '/app/e/$eventSlug/dashboard': {
      id: '/app/e/$eventSlug/dashboard'
      path: '/dashboard'
      fullPath: '/app/e/$eventSlug/dashboard'
      preLoaderRoute: typeof AppEEventSlugDashboardRouteImport
      parentRoute: typeof AppEEventSlugRoute
    }
    '/app/e/$eventSlug/details': {
      id: '/app/e/$eventSlug/details'
      path: '/details'
      fullPath: '/app/e/$eventSlug/details'
      preLoaderRoute: typeof AppEEventSlugDetailsRouteImport
      parentRoute: typeof AppEEventSlugRoute
    }
    '/app/e/$eventSlug/import': {
      id: '/app/e/$eventSlug/import'
      path: '/import'
      fullPath: '/app/e/$eventSlug/import'
      preLoaderRoute: typeof AppEEventSlugImportRouteImport
      parentRoute: typeof AppEEventSlugRoute
    }
    '/app/e/$eventSlug/proposals': {
      id: '/app/e/$eventSlug/proposals'
      path: '/proposals'
      fullPath: '/app/e/$eventSlug/proposals'
      preLoaderRoute: typeof AppEEventSlugProposalsRouteImport
      parentRoute: typeof AppEEventSlugRoute
    }
    '/app/e/$eventSlug/publish': {
      id: '/app/e/$eventSlug/publish'
      path: '/publish'
      fullPath: '/app/e/$eventSlug/publish'
      preLoaderRoute: typeof AppEEventSlugPublishRouteImport
      parentRoute: typeof AppEEventSlugRoute
    }
    '/app/e/$eventSlug/reviews': {
      id: '/app/e/$eventSlug/reviews'
      path: '/reviews'
      fullPath: '/app/e/$eventSlug/reviews'
      preLoaderRoute: typeof AppEEventSlugReviewsRouteImport
      parentRoute: typeof AppEEventSlugRoute
    }
    '/app/e/$eventSlug/settings': {
      id: '/app/e/$eventSlug/settings'
      path: '/settings'
      fullPath: '/app/e/$eventSlug/settings'
      preLoaderRoute: typeof AppEEventSlugSettingsRouteImport
      parentRoute: typeof AppEEventSlugRoute
    }
    '/app/e/$eventSlug/tasks': {
      id: '/app/e/$eventSlug/tasks'
      path: '/tasks'
      fullPath: '/app/e/$eventSlug/tasks'
      preLoaderRoute: typeof AppEEventSlugTasksRouteImport
      parentRoute: typeof AppEEventSlugRoute
    }
    '/app/e/$eventSlug/team': {
      id: '/app/e/$eventSlug/team'
      path: '/team'
      fullPath: '/app/e/$eventSlug/team'
      preLoaderRoute: typeof AppEEventSlugTeamRouteImport
      parentRoute: typeof AppEEventSlugRoute
    }
    '/cfp/$eventSlug/proposal/$proposalId': {
      id: '/cfp/$eventSlug/proposal/$proposalId'
      path: '/proposal/$proposalId'
      fullPath: '/cfp/$eventSlug/proposal/$proposalId'
      preLoaderRoute: typeof CfpEventSlugProposalProposalIdRouteImport
      parentRoute: typeof CfpEventSlugRoute
    }
    '/app/e/$eventSlug/sessions/': {
      id: '/app/e/$eventSlug/sessions/'
      path: '/sessions'
      fullPath: '/app/e/$eventSlug/sessions/'
      preLoaderRoute: typeof AppEEventSlugSessionsIndexRouteImport
      parentRoute: typeof AppEEventSlugRoute
    }
    '/app/e/$eventSlug/sessions/$sessionId': {
      id: '/app/e/$eventSlug/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/app/e/$eventSlug/sessions/$sessionId'
      preLoaderRoute: typeof AppEEventSlugSessionsSessionIdRouteImport
      parentRoute: typeof AppEEventSlugRoute
    }
    '/app/e/$eventSlug/speakers/': {
      id: '/app/e/$eventSlug/speakers/'
      path: '/speakers'
      fullPath: '/app/e/$eventSlug/speakers/'
      preLoaderRoute: typeof AppEEventSlugSpeakersIndexRouteImport
      parentRoute: typeof AppEEventSlugRoute
    }
    '/app/e/$eventSlug/speakers/$eventContactId': {
      id: '/app/e/$eventSlug/speakers/$eventContactId'
      path: '/speakers/$eventContactId'
      fullPath: '/app/e/$eventSlug/speakers/$eventContactId'
      preLoaderRoute: typeof AppEEventSlugSpeakersEventContactIdRouteImport
      parentRoute: typeof AppEEventSlugRoute
    }
  }
}

interface AppEEventSlugRouteChildren {
  AppEEventSlugAgendaRoute: typeof AppEEventSlugAgendaRoute
  AppEEventSlugCfpRoute: typeof AppEEventSlugCfpRoute
  AppEEventSlugCommsRoute: typeof AppEEventSlugCommsRoute
  AppEEventSlugDashboardRoute: typeof AppEEventSlugDashboardRoute
  AppEEventSlugDetailsRoute: typeof AppEEventSlugDetailsRoute
  AppEEventSlugImportRoute: typeof AppEEventSlugImportRoute
  AppEEventSlugProposalsRoute: typeof AppEEventSlugProposalsRoute
  AppEEventSlugPublishRoute: typeof AppEEventSlugPublishRoute
  AppEEventSlugReviewsRoute: typeof AppEEventSlugReviewsRoute
  AppEEventSlugSettingsRoute: typeof AppEEventSlugSettingsRoute
  AppEEventSlugTasksRoute: typeof AppEEventSlugTasksRoute
  AppEEventSlugTeamRoute: typeof AppEEventSlugTeamRoute
  AppEEventSlugIndexRoute: typeof AppEEventSlugIndexRoute
  AppEEventSlugSessionsSessionIdRoute: typeof AppEEventSlugSessionsSessionIdRoute
  AppEEventSlugSpeakersEventContactIdRoute: typeof AppEEventSlugSpeakersEventContactIdRoute
  AppEEventSlugSessionsIndexRoute: typeof AppEEventSlugSessionsIndexRoute
  AppEEventSlugSpeakersIndexRoute: typeof AppEEventSlugSpeakersIndexRoute
}

const AppEEventSlugRouteChildren: AppEEventSlugRouteChildren = {
  AppEEventSlugAgendaRoute: AppEEventSlugAgendaRoute,
  AppEEventSlugCfpRoute: AppEEventSlugCfpRoute,
  AppEEventSlugCommsRoute: AppEEventSlugCommsRoute,
  AppEEventSlugDashboardRoute: AppEEventSlugDashboardRoute,
  AppEEventSlugDetailsRoute: AppEEventSlugDetailsRoute,
  AppEEventSlugImportRoute: AppEEventSlugImportRoute,
  AppEEventSlugProposalsRoute: AppEEventSlugProposalsRoute,
  AppEEventSlugPublishRoute: AppEEventSlugPublishRoute,
  AppEEventSlugReviewsRoute: AppEEventSlugReviewsRoute,
  AppEEventSlugSettingsRoute: AppEEventSlugSettingsRoute,
  AppEEventSlugTasksRoute: AppEEventSlugTasksRoute,
  AppEEventSlugTeamRoute: AppEEventSlugTeamRoute,
  AppEEventSlugIndexRoute: AppEEventSlugIndexRoute,
  AppEEventSlugSessionsSessionIdRoute: AppEEventSlugSessionsSessionIdRoute,
  AppEEventSlugSpeakersEventContactIdRoute:
    AppEEventSlugSpeakersEventContactIdRoute,
  AppEEventSlugSessionsIndexRoute: AppEEventSlugSessionsIndexRoute,
  AppEEventSlugSpeakersIndexRoute: AppEEventSlugSpeakersIndexRoute,
}

const AppEEventSlugRouteWithChildren = AppEEventSlugRoute._addFileChildren(
  AppEEventSlugRouteChildren,
)

interface AppRouteChildren {
  AppHomeRoute: typeof AppHomeRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEEventSlugRoute: typeof AppEEventSlugRouteWithChildren
  AppOrgOrgSlugRoute: typeof AppOrgOrgSlugRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHomeRoute: AppHomeRoute,
  AppIndexRoute: AppIndexRoute,
  AppEEventSlugRoute: AppEEventSlugRouteWithChildren,
  AppOrgOrgSlugRoute: AppOrgOrgSlugRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface CfpEventSlugRouteChildren {
  CfpEventSlugSubmitRoute: typeof CfpEventSlugSubmitRoute
  CfpEventSlugIndexRoute: typeof CfpEventSlugIndexRoute
  CfpEventSlugProposalProposalIdRoute: typeof CfpEventSlugProposalProposalIdRoute
}

const CfpEventSlugRouteChildren: CfpEventSlugRouteChildren = {
  CfpEventSlugSubmitRoute: CfpEventSlugSubmitRoute,
  CfpEventSlugIndexRoute: CfpEventSlugIndexRoute,
  CfpEventSlugProposalProposalIdRoute: CfpEventSlugProposalProposalIdRoute,
}

const CfpEventSlugRouteWithChildren = CfpEventSlugRoute._addFileChildren(
  CfpEventSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CfpEventSlugRoute: CfpEventSlugRouteWithChildren,
  ESlugRoute: ESlugRoute,
  EmbedSlugRoute: EmbedSlugRoute,
  InviteTokenRoute: InviteTokenRoute,
  PortalEventSlugRoute: PortalEventSlugRoute,
  EmbedWEmbedIdRoute: EmbedWEmbedIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
